# Application Name
spring.application.name=TransporterAssignment

# H2 Database Configuration (In-Memory)
spring.datasource.url=jdbc:h2:mem:freightfoxdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Console (so you can view the DB in browser)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL queries in the console (good for debugging)
spring.jpa.show-sql=true

# Server Port (Optional, defaults to 8080)
server.port=8080